In [1]:
import numpy as np

1. Tạo numpy array arr có giá trị từ 0-9. Hiển thị các phần tử có trong arr, xem kiểu dữ liệu và kích thước của arr.
2. Từ array arr ở câu 1 => tạo arr_odd và arr_even.
3. Từ array arr ở câu 1 => tạo arr_update_1 với các phần tử chẵn giữ nguyên, các phần tử lẻ thay bằng 100.

In [3]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr.dtype

dtype('int64')

In [9]:
arr_odd = arr[arr % 2 != 0]
arr_odd

array([1, 3, 5, 7, 9])

In [10]:
arr_even = arr[arr % 2 == 0]
arr_even

array([0, 2, 4, 6, 8])

In [14]:
arr[arr[arr % 2 !=0]] = 100
arr_update_1 = arr.copy()
arr_update_1

array([  0, 100,   2, 100,   4, 100,   6, 100,   8, 100])

1. Cho 2 array arr_a = [1,2,3,2,3,4,3,4,5,6] và arr_b = [7,2,10,2,7,4,9,4,9,8], tạo array arr_c chỉ lấy duy nhất các phần tử xuất hiện ở cả arr_a và arr_b.
2. Từ arr_a và arr_b ở câu 1 => Tạo arr_d chứa các phần tử chỉ xuất hiện ở arr_a.
3. Cho arr_e = np.array([2, 6, 1, 9, 10, 3, 27, 8, 6, 25, 16]), hãy tạo arr_f chỉ chứa các phần tử có giá trị từ 5 đến 10 của arr_e.


In [22]:
arr_a = np.array([1,2,3,2,3,4,3,4,5,6])
arr_b = np.array([7,2,10,2,7,4,9,4,9,8])
arr_c = np.intersect1d(arr_a,arr_b)
arr_c



array([2, 4])

In [25]:
arr_d = arr_a[~np.isin(arr_a,arr_b)]
arr_d

array([1, 3, 3, 3, 5, 6])

In [26]:
arr_e = np.array([2, 6, 1, 9, 10, 3, 27, 8, 6, 25, 16])
arr_e

array([ 2,  6,  1,  9, 10,  3, 27,  8,  6, 25, 16])

In [29]:
arr_f = arr_e[(arr_e >= 5) & (arr_e <= 10)]
arr_f

array([ 6,  9, 10,  8,  6])

In [ ]:
1. Tạo arr_zeros có 10 phần tử 0, cập nhật phần tử ở vị trí thứ 5 là 1.
2. Tạo arr_h có giá trị từ 10 đến 24. In danh sách các phần tử theo tứ tự đảo ngược của arr_h.
3. Cho arr_k = np.array([1, 2, 0, 8, 2, 0, 1, 3, 0, 5, 0]), tạo arr_l từ arr_k với các phần tử khác 0.
4. Từ arr_l của câu 3, thêm 2 phần tử có giá trị là 10 và 20 vào cuối array.
5. Từ array của câu 4, thêm phần tử có giá trị 100 vào vị trí có index = 5.
6. Từ array của câu 5, xóa các phần tử tại vị trí có index = 0, 1, 2.

In [33]:
arr_zeros = np.zeros(10,dtype = np.int32)
arr_zeros[4] = 1
arr_zeros

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0], dtype=int32)

In [39]:
arr_h = np.arange(10,25)
arr_h[::-1]

array([24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

In [40]:
arr_k = np.array([1, 2, 0, 8, 2, 0, 1, 3, 0, 5, 0])

In [49]:
arr_l = arr_k[arr_k != 0]

In [50]:
arr_l

array([1, 2, 8, 2, 1, 3, 5])

In [51]:
arr_l =np.append(arr_l,[10,20])

In [52]:
arr_l

array([ 1,  2,  8,  2,  1,  3,  5, 10, 20])

In [53]:
arr_l = np.insert(arr_l,5,100)
arr_l

array([  1,   2,   8,   2,   1, 100,   3,   5,  10,  20])

In [54]:
arr_l = np.delete(arr_l,[0,1,2])

In [55]:
arr_l

array([  2,   1, 100,   3,   5,  10,  20])

Cho tập tin dữ liệu heights_1.txt, weights_1.txt => hãy chép dữ liệu từ tập tin này vào list là height, weight, và thực hiện các yêu cầu sau:
1. Tạo numpy array arr_height từ list height.
2. Tạo numpy array arr_weight từ list weight.
3. Cho hệ số quy đổi từ inch sang m là 0.0254, tạo arr_height_m dựa trên công thức: arr_height * hệ số quy đổi.
4. Cho hệ số quy đổi từ pound sang kg là 0.453592, tạo arr_weight_kg dựa trên công thức: arr_weight * hệ số quy đổi.
5. Tính BMI của arr_height_m và arr_weight_kg theo công thức BMI = Cân nặng / (Chiều cao * Chiều cao), và lưu vào arr_bmi.
6. Cho biết giá trị cân nặng ở vị trí index = 50 trong arr_weight_kg
7. Tạo arr_height_m_100 gồm các phần tử có vị trí index từ 100 đến 110 (lấy cả index 110) trong arr_height_m
8. Cho biết các cầu thủ bóng chày có bmi < 21 trong arr_bmi
9. Cho biết chiều cao trung bình và cân nặng trung bình của các cầu thủ
10. Cho biết chiều cao và cân nặng lớn nhất của các cầu thủ
11. Cho biết chiều cao và cân nặng nhỏ nhất của các cầu thủ

In [60]:
with open('heights_1.txt') as f:
    content = f.read()
height = eval(content)


In [59]:
with open('weights_1.txt') as f:
    content = f.read()
weight = eval(content)

In [61]:
arr_height = np.array(height)
arr_height

array([74, 74, 72, ..., 75, 75, 73])

In [62]:
arr_weight = np.array(weight)
arr_weight

array([180, 215, 210, ..., 205, 190, 195])

In [63]:
arr_height_m =  arr_height * 0.0254
arr_height_m

array([1.8796, 1.8796, 1.8288, ..., 1.905 , 1.905 , 1.8542])

In [64]:
arr_weight_kg = arr_weight * 0.453592
arr_weight_kg

array([81.64656, 97.52228, 95.25432, ..., 92.98636, 86.18248, 88.45044])

In [65]:
arr_bmi = arr_weight_kg / (arr_height_m * arr_height_m)
arr_bmi

array([23.11037639, 27.60406069, 28.48080465, ..., 25.62295933,
       23.74810865, 25.72686361])

In [66]:
arr_height_m_100 = arr_height_m[100:111]
arr_height_m_100

array([1.8542, 1.8796, 1.8288, 1.8542, 1.7526, 1.8288, 1.8542, 1.905 ,
       1.905 , 1.8542, 1.8288])

In [67]:
arr_bmi[arr_bmi < 21]

array([20.54255679, 20.54255679, 20.69282047, 20.69282047, 20.34343189,
       20.34343189, 20.69282047, 20.15883472, 19.4984471 , 20.69282047,
       20.9205219 ])

In [68]:
arr_height_m.mean()

np.float64(1.8717172413793102)

In [69]:
arr_weight_kg.mean()

np.float64(91.33019058916256)

In [70]:
arr_height_m.max()

np.float64(2.1082)

In [71]:
arr_weight_kg.max()

np.float64(131.54167999999999)

In [72]:
arr_height_m.min()

np.float64(1.7018)

In [73]:
arr_weight_kg.min()

np.float64(68.0388)

1. Tạo array arr có kích thước 3x3 với các giá trị True
2. Cho arr_1D = np.array([0 1 2 3 4 5 6 7 8]). Tạo array 2 chiều có kích thước 3x3 từ arr_1D, và lưu vào arr_2D Trong arr_2D, chuyển cột 1 sang cột 3 và ngược lại.
3. Từ arr_2D của câu 2 (sau khi đổi thứ tự cột), chuyển dòng 1 sang dòng 2 và ngược lại.
4. Từ arr_2D của câu 3, đảo ngược các dòng của arr_2D.
5. Từ arr_2D của câu 4, đảo ngược các cột của arr_2D.
6. Cho arr_2D_null = np.array([[1, 2, 3], [np.NaN, 5, 6], [7, np.NaN, 9], [4, 5, 6]]), Kiểm tra trong array có giá trị rỗng không?
7. Từ arr_2D_null của câu 6, thay thế giá trị null bằng 0.

In [75]:
arr = np.ones((3,3),dtype=bool)
arr

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [78]:
arr_1D = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
arr_2D = arr_1D.reshape((3,3))
arr_2D

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [79]:
arr_2D[:,[0,2]] = arr_2D[:,[2,0]]
arr_2D

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [80]:
arr_2D[[0,1],:] = arr_2D[[1,0],:]
arr_2D

array([[5, 4, 3],
       [2, 1, 0],
       [8, 7, 6]])

In [81]:
arr_2D[::-1]

array([[8, 7, 6],
       [2, 1, 0],
       [5, 4, 3]])

In [82]:
arr_2D[:,::-1]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [84]:
arr_2D_null = np.array([[1, 2, 3], [np.nan, 5, 6], [7, np.nan, 9], [4, 5, 6]])

In [87]:
arr_2D_null[np.isnan(arr_2D_null)] = 0

In [89]:
arr_2D_null

array([[1., 2., 3.],
       [0., 5., 6.],
       [7., 0., 9.],
       [4., 5., 6.]])

In [90]:
np.isnan(arr_2D_null).any()

np.False_